# Site Settings
title: NYS Tenant Rights
description: Devoted to informing New York State tenants of their legal rights responsibilities and entitlements.
url: http://rramsland.github.io/Tenant-Rights
pathname: Tenant-Rights

# Build Settings
markdown: kramdown
permalink: pretty
